name: "bert_onnx_2"
platform: "onnxruntime_onnx"
max_batch_size: 8
default_model_filename: "bert_base_4_labels.onnx"
version_policy: {
  specific: {
    versions: [ 1 ]
  }
}

input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ 128 ]
  },
  {
    name: "token_type_ids"
    data_type: TYPE_INT64
    dims: [ 128 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ 128 ]
  }
]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [ -1, 768 ]
  }
]

dynamic_batching { 
  preferred_batch_size: [ 1, 4, 8 ]
  max_queue_delay_microseconds: 500000
}