name: "pii_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 32
default_model_filename: "model_10labels_256seqV3.onnx"
version_policy: {
  specific: {
    versions: [ 1 ]
  }
}

input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ 256 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ 256 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]

dynamic_batching { 
  preferred_batch_size: [ 1, 4, 8, 16 ]
  max_queue_delay_microseconds: 50000
}

#optimization { execution_accelerators {
#  gpu_execution_accelerator : [ { name : "tensorrt" } ]
#}}