# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rrequest.proto\"#\n\x12StringArrayPayload\x12\r\n\x05value\x18\x01 \x03(\t\"t\n\x10\x43udaArrayPayload\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0f\n\x07strides\x18\x02 \x03(\x05\x12\x0f\n\x07typestr\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x04\x12\x10\n\x08readonly\x18\x05 \x01(\x08\x12\x0f\n\x07version\x18\x06 \x01(\x05\"d\n\x07Payload\x12(\n\tstr_array\x18\x01 \x01(\x0b\x32\x13.StringArrayPayloadH\x00\x12\'\n\ncupy_array\x18\x02 \x01(\x0b\x32\x11.CudaArrayPayloadH\x00\x42\x06\n\x04\x64\x61ta\"\x8c\x01\n\nStageInput\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12)\n\x07payload\x18\x03 \x03(\x0b\x32\x18.StageInput.PayloadEntry\x1a\x38\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Payload:\x02\x38\x01\"\x8e\x01\n\x0bStageOutput\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12*\n\x07payload\x18\x03 \x03(\x0b\x32\x19.StageOutput.PayloadEntry\x1a\x38\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Payload:\x02\x38\x01\x32=\n\x08Pipeline\x12\x31\n\x12QueuePreprocessing\x12\x0b.StageInput\x1a\x0c.StageOutput\"\x00\x62\x06proto3'
)




_STRINGARRAYPAYLOAD = _descriptor.Descriptor(
  name='StringArrayPayload',
  full_name='StringArrayPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StringArrayPayload.value', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=52,
)


_CUDAARRAYPAYLOAD = _descriptor.Descriptor(
  name='CudaArrayPayload',
  full_name='CudaArrayPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='CudaArrayPayload.shape', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strides', full_name='CudaArrayPayload.strides', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='typestr', full_name='CudaArrayPayload.typestr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='CudaArrayPayload.data', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='readonly', full_name='CudaArrayPayload.readonly', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='CudaArrayPayload.version', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=170,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='str_array', full_name='Payload.str_array', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cupy_array', full_name='Payload.cupy_array', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='Payload.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=172,
  serialized_end=272,
)


_STAGEINPUT_PAYLOADENTRY = _descriptor.Descriptor(
  name='PayloadEntry',
  full_name='StageInput.PayloadEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='StageInput.PayloadEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='StageInput.PayloadEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=415,
)

_STAGEINPUT = _descriptor.Descriptor(
  name='StageInput',
  full_name='StageInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='StageInput.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='StageInput.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='StageInput.payload', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STAGEINPUT_PAYLOADENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=415,
)


_STAGEOUTPUT_PAYLOADENTRY = _descriptor.Descriptor(
  name='PayloadEntry',
  full_name='StageOutput.PayloadEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='StageOutput.PayloadEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='StageOutput.PayloadEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=415,
)

_STAGEOUTPUT = _descriptor.Descriptor(
  name='StageOutput',
  full_name='StageOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='StageOutput.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='StageOutput.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='StageOutput.payload', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STAGEOUTPUT_PAYLOADENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=560,
)

_PAYLOAD.fields_by_name['str_array'].message_type = _STRINGARRAYPAYLOAD
_PAYLOAD.fields_by_name['cupy_array'].message_type = _CUDAARRAYPAYLOAD
_PAYLOAD.oneofs_by_name['data'].fields.append(
  _PAYLOAD.fields_by_name['str_array'])
_PAYLOAD.fields_by_name['str_array'].containing_oneof = _PAYLOAD.oneofs_by_name['data']
_PAYLOAD.oneofs_by_name['data'].fields.append(
  _PAYLOAD.fields_by_name['cupy_array'])
_PAYLOAD.fields_by_name['cupy_array'].containing_oneof = _PAYLOAD.oneofs_by_name['data']
_STAGEINPUT_PAYLOADENTRY.fields_by_name['value'].message_type = _PAYLOAD
_STAGEINPUT_PAYLOADENTRY.containing_type = _STAGEINPUT
_STAGEINPUT.fields_by_name['payload'].message_type = _STAGEINPUT_PAYLOADENTRY
_STAGEOUTPUT_PAYLOADENTRY.fields_by_name['value'].message_type = _PAYLOAD
_STAGEOUTPUT_PAYLOADENTRY.containing_type = _STAGEOUTPUT
_STAGEOUTPUT.fields_by_name['payload'].message_type = _STAGEOUTPUT_PAYLOADENTRY
DESCRIPTOR.message_types_by_name['StringArrayPayload'] = _STRINGARRAYPAYLOAD
DESCRIPTOR.message_types_by_name['CudaArrayPayload'] = _CUDAARRAYPAYLOAD
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.message_types_by_name['StageInput'] = _STAGEINPUT
DESCRIPTOR.message_types_by_name['StageOutput'] = _STAGEOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringArrayPayload = _reflection.GeneratedProtocolMessageType('StringArrayPayload', (_message.Message,), {
  'DESCRIPTOR' : _STRINGARRAYPAYLOAD,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:StringArrayPayload)
  })
_sym_db.RegisterMessage(StringArrayPayload)

CudaArrayPayload = _reflection.GeneratedProtocolMessageType('CudaArrayPayload', (_message.Message,), {
  'DESCRIPTOR' : _CUDAARRAYPAYLOAD,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:CudaArrayPayload)
  })
_sym_db.RegisterMessage(CudaArrayPayload)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:Payload)
  })
_sym_db.RegisterMessage(Payload)

StageInput = _reflection.GeneratedProtocolMessageType('StageInput', (_message.Message,), {

  'PayloadEntry' : _reflection.GeneratedProtocolMessageType('PayloadEntry', (_message.Message,), {
    'DESCRIPTOR' : _STAGEINPUT_PAYLOADENTRY,
    '__module__' : 'request_pb2'
    # @@protoc_insertion_point(class_scope:StageInput.PayloadEntry)
    })
  ,
  'DESCRIPTOR' : _STAGEINPUT,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:StageInput)
  })
_sym_db.RegisterMessage(StageInput)
_sym_db.RegisterMessage(StageInput.PayloadEntry)

StageOutput = _reflection.GeneratedProtocolMessageType('StageOutput', (_message.Message,), {

  'PayloadEntry' : _reflection.GeneratedProtocolMessageType('PayloadEntry', (_message.Message,), {
    'DESCRIPTOR' : _STAGEOUTPUT_PAYLOADENTRY,
    '__module__' : 'request_pb2'
    # @@protoc_insertion_point(class_scope:StageOutput.PayloadEntry)
    })
  ,
  'DESCRIPTOR' : _STAGEOUTPUT,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:StageOutput)
  })
_sym_db.RegisterMessage(StageOutput)
_sym_db.RegisterMessage(StageOutput.PayloadEntry)


_STAGEINPUT_PAYLOADENTRY._options = None
_STAGEOUTPUT_PAYLOADENTRY._options = None

_PIPELINE = _descriptor.ServiceDescriptor(
  name='Pipeline',
  full_name='Pipeline',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=562,
  serialized_end=623,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueuePreprocessing',
    full_name='Pipeline.QueuePreprocessing',
    index=0,
    containing_service=None,
    input_type=_STAGEINPUT,
    output_type=_STAGEOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PIPELINE)

DESCRIPTOR.services_by_name['Pipeline'] = _PIPELINE

# @@protoc_insertion_point(module_scope)
