# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import request_pb2 as request__pb2


class PipelineStub(object):
    """rpc ProcessRequest(PipelineRequest) returns PipelineResponse {}
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueuePreprocessing = channel.unary_unary(
                '/Pipeline/QueuePreprocessing',
                request_serializer=request__pb2.StageInput.SerializeToString,
                response_deserializer=request__pb2.StageOutput.FromString,
                )


class PipelineServicer(object):
    """rpc ProcessRequest(PipelineRequest) returns PipelineResponse {}
    """

    def QueuePreprocessing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueuePreprocessing': grpc.unary_unary_rpc_method_handler(
                    servicer.QueuePreprocessing,
                    request_deserializer=request__pb2.StageInput.FromString,
                    response_serializer=request__pb2.StageOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Pipeline', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pipeline(object):
    """rpc ProcessRequest(PipelineRequest) returns PipelineResponse {}
    """

    @staticmethod
    def QueuePreprocessing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Pipeline/QueuePreprocessing',
            request__pb2.StageInput.SerializeToString,
            request__pb2.StageOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
