name: "bert_trt"
platform: "tensorrt_plan"
max_batch_size: 8
default_model_filename: "triton_bert_large_128-b8-b9.engine"

input [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ 128 ]
  },
  {
    name: "segment_ids"
    data_type: TYPE_INT32
    dims: [ 128 ]
  },
  {
    name: "input_mask"
    data_type: TYPE_INT32
    dims: [ 128 ]
  }
]
output [
  {
    name: "cls_squad_logits"
    data_type: TYPE_FP32
    dims: [ 128, 2, 1, 1 ]
  }
]

dynamic_batching { 
  preferred_batch_size: [ 1, 4, 8 ]
  max_queue_delay_microseconds: 500000
}